---
kind: pipeline
name: test

steps:
  - name: lint
    image: golang:1.15
    commands:
      - make lint

  - name: test
    image: golang:1.15
    commands:
      - make test

  - name: fetch
    image: docker:git
    commands:
      - git fetch --tags

  - name: build
    image: goreleaser/goreleaser:v0.146.0
    commands:
      - apk add --no-cache make
      - make build
      - make is-git-dirty

trigger:
  event:
    - push
    - pull_request
    - tag

---
kind: pipeline
name: coverage

steps:
  - name: coverage
    image: golang:1.15
    environment:
      COVERALLS_TOKEN:
        from_secret: COVERALLS_TOKEN
    commands:
      - make coverage
      - make publish-coveralls

trigger:
  repo:
    - mvisonneau/ocalver
  event:
    - push
    - tag

---
kind: pipeline
name: release

steps:
  - name: fetch
    image: docker:git
    commands:
      - git fetch --tags

  - name: release
    image: goreleaser/goreleaser:v0.146.0
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
    commands:
      - apk add --no-cache make
      - make release

  - name: gopkg-refresh
    image: curlimages/curl
    commands:
      - curl https://sum.golang.org/lookup/github.com/mvisonneau/ocalver@${DRONE_TAG}

trigger:
  repo:
    - mvisonneau/ocalver
  event:
    - tag

depends_on:
  - test
  - coverage

---
kind: signature
hmac: 8a69a0c9e42cb976d87ca8fcd9376f4edbb24986c7a2077988c4d1c2359acde5

...
