before:
  hooks:
    - go mod download

builds:
  - main: ./cmd/ocalver
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm64
    flags:
      - -trimpath
    ignore:
      - goos: darwin
        goarch: 386

archives:
  - name_template: '{{ .ProjectName }}_edge_{{ .Os }}_{{ .Arch }}'
    format_overrides:
      - goos: windows
        format: zip

release:
  disable: true

snapcrafts:
  - summary: Opinionated CalVer generator
    description: Purpose of this tool is to generate CalVer formatted values to use as tags for your git projects.
    license: Apache-2.0
    confinement: strict
    grade: devel
    apps:
      ocalver:
        plugs: [home]

dockers:
  - image_templates:
      - 'docker.io/mvisonneau/ocalver:latest-amd64'
      - 'ghcr.io/mvisonneau/ocalver:latest-amd64'
    ids: [ocalver]
    dockerfile: Dockerfile
    build_flag_templates:
      - --build-arg=ARCH=amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/mvisonneau/ocalver
      - --label=org.opencontainers.image.source=https://github.com/mvisonneau/ocalver
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=Apache-2.0

  - image_templates:
      - 'docker.io/mvisonneau/ocalver:latest-arm64v8'
      - 'ghcr.io/mvisonneau/ocalver:latest-arm64v8'
    ids: [ocalver]
    goarch: arm64
    dockerfile: Dockerfile
    build_flag_templates:
      - --build-arg=ARCH=arm64v8
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/mvisonneau/ocalver
      - --label=org.opencontainers.image.source=https://github.com/mvisonneau/ocalver
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=Apache-2.0

docker_manifests:
  - name_template: docker.io/mvisonneau/ocalver:latest
    image_templates:
      - docker.io/mvisonneau/ocalver:latest-amd64
      - docker.io/mvisonneau/ocalver:latest-arm64v8

  - name_template: ghcr.io/mvisonneau/ocalver:latest
    image_templates:
      - ghcr.io/mvisonneau/ocalver:latest-amd64
      - ghcr.io/mvisonneau/ocalver:latest-arm64v8

signs:
  - artifacts: checksum
    args:
      [
        '-u',
        'C09CA9F71C5C988E65E3E5FCADEA38EDC46F25BE',
        '--output',
        '${signature}',
        '--detach-sign',
        '${artifact}',
      ]

checksum:
  name_template: '{{ .ProjectName }}_edge_sha512sums.txt'
  algorithm: sha512

changelog:
  skip: true
